// Auto-generated from your tagged photos. 125 items (89 residential, 36 commercial).
// Media lives in /public/assets/projects/ — bundled, always loads.
const P = (f) => `/assets/projects/${f}`;

export const gallery = [
  { file: P("item-001.jpg"), cat: "residential", type: "image" },
  { file: P("item-002.jpg"), cat: "residential", type: "image" },
  { file: P("item-003.jpg"), cat: "residential", type: "image" },
  { file: P("item-004.mp4"), cat: "residential", type: "video" },
  { file: P("item-005.jpg"), cat: "residential", type: "image" },
  { file: P("item-006.jpg"), cat: "commercial", type: "image" },
  { file: P("item-007.mp4"), cat: "commercial", type: "video" },
  { file: P("item-008.jpg"), cat: "residential", type: "image" },
  { file: P("item-009.jpg"), cat: "residential", type: "image" },
  { file: P("item-010.jpg"), cat: "residential", type: "image" },
  { file: P("item-011.mp4"), cat: "residential", type: "video" },
  { file: P("item-012.jpg"), cat: "commercial", type: "image" },
  { file: P("item-013.jpg"), cat: "residential", type: "image" },
  { file: P("item-014.jpg"), cat: "residential", type: "image" },
  { file: P("item-015.jpg"), cat: "commercial", type: "image" },
  { file: P("item-016.jpg"), cat: "commercial", type: "image" },
  { file: P("item-017.jpg"), cat: "residential", type: "image" },
  { file: P("item-018.jpg"), cat: "residential", type: "image" },
  { file: P("item-019.jpg"), cat: "residential", type: "image" },
  { file: P("item-020.jpg"), cat: "residential", type: "image" },
  { file: P("item-021.jpg"), cat: "residential", type: "image" },
  { file: P("item-022.jpg"), cat: "residential", type: "image" },
  { file: P("item-023.jpg"), cat: "commercial", type: "image" },
  { file: P("item-024.jpg"), cat: "commercial", type: "image" },
  { file: P("item-025.jpg"), cat: "commercial", type: "image" },
  { file: P("item-026.jpg"), cat: "commercial", type: "image" },
  { file: P("item-027.jpg"), cat: "residential", type: "image" },
  { file: P("item-028.jpg"), cat: "residential", type: "image" },
  { file: P("item-029.jpg"), cat: "residential", type: "image" },
  { file: P("item-030.jpg"), cat: "residential", type: "image" },
  { file: P("item-031.jpg"), cat: "residential", type: "image" },
  { file: P("item-032.jpg"), cat: "residential", type: "image" },
  { file: P("item-033.jpg"), cat: "residential", type: "image" },
  { file: P("item-034.jpg"), cat: "commercial", type: "image" },
  { file: P("item-035.jpg"), cat: "commercial", type: "image" },
  { file: P("item-036.jpg"), cat: "residential", type: "image" },
  { file: P("item-037.jpg"), cat: "residential", type: "image" },
  { file: P("item-038.jpg"), cat: "residential", type: "image" },
  { file: P("item-039.jpg"), cat: "residential", type: "image" },
  { file: P("item-040.jpg"), cat: "residential", type: "image" },
  { file: P("item-041.mp4"), cat: "residential", type: "video" },
  { file: P("item-042.jpg"), cat: "residential", type: "image" },
  { file: P("item-043.jpg"), cat: "residential", type: "image" },
  { file: P("item-044.jpg"), cat: "residential", type: "image" },
  { file: P("item-045.jpg"), cat: "residential", type: "image" },
  { file: P("item-046.jpg"), cat: "residential", type: "image" },
  { file: P("item-047.mp4"), cat: "residential", type: "video" },
  { file: P("item-048.jpg"), cat: "residential", type: "image" },
  { file: P("item-049.mp4"), cat: "residential", type: "video" },
  { file: P("item-050.jpg"), cat: "residential", type: "image" },
  { file: P("item-051.jpg"), cat: "residential", type: "image" },
  { file: P("item-052.mp4"), cat: "residential", type: "video" },
  { file: P("item-053.jpg"), cat: "residential", type: "image" },
  { file: P("item-054.mp4"), cat: "commercial", type: "video" },
  { file: P("item-055.jpg"), cat: "commercial", type: "image" },
  { file: P("item-056.mp4"), cat: "commercial", type: "video" },
  { file: P("item-057.jpg"), cat: "residential", type: "image" },
  { file: P("item-058.mp4"), cat: "residential", type: "video" },
  { file: P("item-059.jpg"), cat: "commercial", type: "image" },
  { file: P("item-060.mp4"), cat: "commercial", type: "video" },
  { file: P("item-061.jpg"), cat: "commercial", type: "image" },
  { file: P("item-062.mp4"), cat: "commercial", type: "video" },
  { file: P("item-063.mp4"), cat: "commercial", type: "video" },
  { file: P("item-064.jpg"), cat: "residential", type: "image" },
  { file: P("item-065.jpg"), cat: "residential", type: "image" },
  { file: P("item-066.jpg"), cat: "residential", type: "image" },
  { file: P("item-067.jpg"), cat: "residential", type: "image" },
  { file: P("item-068.jpg"), cat: "residential", type: "image" },
  { file: P("item-069.jpg"), cat: "residential", type: "image" },
  { file: P("item-070.jpg"), cat: "residential", type: "image" },
  { file: P("item-071.jpg"), cat: "residential", type: "image" },
  { file: P("item-072.jpg"), cat: "residential", type: "image" },
  { file: P("item-073.mp4"), cat: "commercial", type: "video" },
  { file: P("item-074.jpg"), cat: "residential", type: "image" },
  { file: P("item-075.jpg"), cat: "commercial", type: "image" },
  { file: P("item-076.jpg"), cat: "commercial", type: "image" },
  { file: P("item-077.jpg"), cat: "residential", type: "image" },
  { file: P("item-078.jpg"), cat: "residential", type: "image" },
  { file: P("item-079.jpg"), cat: "residential", type: "image" },
  { file: P("item-080.jpg"), cat: "residential", type: "image" },
  { file: P("item-081.jpg"), cat: "residential", type: "image" },
  { file: P("item-082.mp4"), cat: "commercial", type: "video" },
  { file: P("item-083.jpg"), cat: "commercial", type: "image" },
  { file: P("item-084.mp4"), cat: "commercial", type: "video" },
  { file: P("item-085.jpg"), cat: "commercial", type: "image" },
  { file: P("item-086.mp4"), cat: "commercial", type: "video" },
  { file: P("item-087.jpg"), cat: "commercial", type: "image" },
  { file: P("item-088.mp4"), cat: "commercial", type: "video" },
  { file: P("item-089.jpg"), cat: "residential", type: "image" },
  { file: P("item-090.jpg"), cat: "residential", type: "image" },
  { file: P("item-091.jpg"), cat: "residential", type: "image" },
  { file: P("item-092.jpg"), cat: "residential", type: "image" },
  { file: P("item-093.jpg"), cat: "residential", type: "image" },
  { file: P("item-094.mp4"), cat: "residential", type: "video" },
  { file: P("item-095.jpg"), cat: "residential", type: "image" },
  { file: P("item-096.mp4"), cat: "residential", type: "video" },
  { file: P("item-097.jpg"), cat: "residential", type: "image" },
  { file: P("item-098.jpg"), cat: "residential", type: "image" },
  { file: P("item-099.jpg"), cat: "residential", type: "image" },
  { file: P("item-100.jpg"), cat: "residential", type: "image" },
  { file: P("item-101.jpg"), cat: "residential", type: "image" },
  { file: P("item-102.jpg"), cat: "residential", type: "image" },
  { file: P("item-103.jpg"), cat: "residential", type: "image" },
  { file: P("item-104.jpg"), cat: "residential", type: "image" },
  { file: P("item-105.jpg"), cat: "residential", type: "image" },
  { file: P("item-106.jpg"), cat: "residential", type: "image" },
  { file: P("item-107.jpg"), cat: "residential", type: "image" },
  { file: P("item-108.mp4"), cat: "residential", type: "video" },
  { file: P("item-109.jpg"), cat: "commercial", type: "image" },
  { file: P("item-110.jpg"), cat: "commercial", type: "image" },
  { file: P("item-111.jpg"), cat: "commercial", type: "image" },
  { file: P("item-112.mp4"), cat: "residential", type: "video" },
  { file: P("item-113.jpg"), cat: "residential", type: "image" },
  { file: P("item-114.jpg"), cat: "residential", type: "image" },
  { file: P("item-115.jpg"), cat: "residential", type: "image" },
  { file: P("item-116.jpg"), cat: "commercial", type: "image" },
  { file: P("item-117.jpg"), cat: "residential", type: "image" },
  { file: P("item-118.jpg"), cat: "residential", type: "image" },
  { file: P("item-119.jpg"), cat: "commercial", type: "image" },
  { file: P("item-120.jpg"), cat: "residential", type: "image" },
  { file: P("item-121.jpg"), cat: "residential", type: "image" },
  { file: P("item-122.jpg"), cat: "residential", type: "image" },
  { file: P("item-123.jpg"), cat: "residential", type: "image" },
  { file: P("item-124.jpg"), cat: "commercial", type: "image" },
  { file: P("item-125.jpg"), cat: "commercial", type: "image" },
];

export const featured = [
  { img: P("item-001.jpg"), tag: "Residential", title: "Residential Interior", desc: "A warm, considered living space designed and executed end to end." },
  { img: P("item-002.jpg"), tag: "Residential", title: "Residential Interior", desc: "Layered lighting, natural materials, and calm, liveable detailing." },
  { img: P("item-003.jpg"), tag: "Residential", title: "Residential Interior", desc: "Bespoke joinery and finishes tailored to how the family lives." },
  { img: P("item-006.jpg"), tag: "Commercial", title: "Commercial Space", desc: "A brand-forward commercial fit-out built for footfall and function." },
  { img: P("item-012.jpg"), tag: "Commercial", title: "Commercial Space", desc: "Durable, striking materials that make the space work every day." },
];

export const filters = [
  { key: 'all', label: 'All' },
  { key: 'residential', label: 'Residential' },
  { key: 'commercial', label: 'Commercial' },
];

// atmospheric stills reused in panels (first residential + commercial images)
export const scenes = {
  living: P("item-001.jpg"),
  commercial: P("item-006.jpg"),
};
